name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=s0lex/base-utils
          COMMIT_SHA=$(git rev-parse --short HEAD)
          RUN_NUMBER=${{ github.run_number }}

          # Build the image with multiple tags
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_SHA -t $IMAGE_NAME:$RUN_NUMBER .

          # Push all tags in a single command
          docker push --all-tags $IMAGE_NAME
